// Generated by BUCKLESCRIPT VERSION 4.0.7000, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bsb-native/lib/js/curry.js");
var Spring = require("./Spring.js");

function spring(dampingRatio, frequencyResponseMs, $staropt$star, update, finish) {
  var initialVelocity = $staropt$star !== undefined ? $staropt$star : 0;
  var config_000 = /* damping */Spring.perfectDamp(500);
  var config = /* record */[
    config_000,
    /* stiffness */500,
    /* restDisplacementThreshold */0.001,
    /* restVelocityThreshold */0.001
  ];
  var state = /* record */[/* contents */Spring.init(initialVelocity, config)];
  var lastTime = /* record */[/* contents */Date.now()];
  Date.now();
  var loop = function (param) {
    Curry._1(update, state[0][/* currentValue */2]);
    var now = Date.now();
    var timeDelta = now - lastTime[0];
    state[0] = Spring.advance(timeDelta, state[0]);
    lastTime[0] = now;
    if (Spring.isAtRest(state[0])) {
      return Curry._1(finish, /* () */0);
    } else {
      requestAnimationFrame(loop);
      return /* () */0;
    }
  };
  return loop(/* () */0);
}

exports.spring = spring;
/* No side effect */
