// Generated by BUCKLESCRIPT VERSION 4.0.7000, PLEASE EDIT WITH CARE
'use strict';

var List = require("bsb-native/lib/js/list.js");
var Block = require("bsb-native/lib/js/block.js");
var Curry = require("bsb-native/lib/js/curry.js");
var Layout = require("../Layout.bs.js");
var Random = require("bsb-native/lib/js/random.js");
var Animate = require("./Animate.bs.js");
var FluidDom = require("./FluidDom.bs.js");
var Belt_Debug = require("bsb-native/lib/js/belt_Debug.js");
var Caml_int32 = require("bsb-native/lib/js/caml_int32.js");
var Pervasives = require("bsb-native/lib/js/pervasives.js");
var Js_primitive = require("bsb-native/lib/js/js_primitive.js");
var Caml_builtin_exceptions = require("bsb-native/lib/js/caml_builtin_exceptions.js");

Belt_Debug.setupChromeDebugger(/* () */0);

var Style = /* module */[];

var str = FluidDom.Fluid[/* string */29];

function translate(node, dx, offset) {
  return Animate.spring(1, 10, undefined, (function (amount) {
                node.style.transform = "translateX(" + (Pervasives.string_of_float((1 - amount) * dx + offset) + "px)");
                return /* () */0;
              }), (function (param) {
                return /* () */0;
              }));
}

function fade(node, out) {
  return Animate.spring(1, 10, undefined, (function (amount) {
                node.style.opacity = out ? amount : 1 - amount;
                return /* () */0;
              }), (function (param) {
                if (out) {
                  node.parentNode.removeChild(node);
                  return /* () */0;
                } else {
                  return 0;
                }
              }));
}

function toggle(on, off, hooks) {
  var match = Curry._2(FluidDom.Fluid[/* Hooks */27][/* useState */3], false, hooks);
  var match$1 = match[0];
  var setOn = match$1[1];
  var isOn = match$1[0];
  console.log("Is On", isOn);
  if (isOn) {
    return Curry._1(on, (function (param) {
                  return Curry._1(setOn, false);
                }));
  } else {
    return Curry._1(off, (function (param) {
                  return Curry._1(setOn, true);
                }));
  }
}

function awesomeComponent(value, toString, hooks) {
  var match = Curry._2(FluidDom.Fluid[/* Hooks */27][/* useState */3], "Awesome", hooks);
  var match$1 = match[0];
  var setState = match$1[1];
  var state = match$1[0];
  return Curry.app(FluidDom.Fluid[/* Native */28][/* div */0], [
              undefined,
              /* :: */[
                Curry.app(FluidDom.Fluid[/* Native */28][/* div */0], [
                      undefined,
                      /* :: */[
                        str(undefined, undefined, "Folkx " + (Curry._1(toString, value) + (" " + state))),
                        /* [] */0
                      ],
                      undefined,
                      undefined,
                      undefined,
                      undefined,
                      (function (_evt) {
                          return Curry._1(setState, state + "1");
                        }),
                      undefined,
                      /* () */0
                    ]),
                /* [] */0
              ],
              undefined,
              undefined,
              undefined,
              undefined,
              undefined,
              undefined,
              /* () */0
            ]);
}

function button(text, style, onClick, hooks) {
  return Curry.app(FluidDom.Fluid[/* Native */28][/* button */1], [
              undefined,
              /* :: */[
                str(undefined, undefined, text),
                /* [] */0
              ],
              Layout.style(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, 4, 8, undefined, undefined, undefined, undefined, /* () */0),
              undefined,
              undefined,
              undefined,
              (function (_evt) {
                  return Curry._1(onClick, /* () */0);
                }),
              style,
              /* () */0
            ]);
}

var simple = Curry.app(FluidDom.Fluid[/* Native */28][/* div */0], [
      "awesome",
      /* :: */[
        str(undefined, undefined, "Hello"),
        /* :: */[
          Curry.app(FluidDom.Fluid[/* Native */28][/* div */0], [
                "here",
                /* :: */[
                  Curry.app(FluidDom.Fluid[/* Native */28][/* div */0], [
                        undefined,
                        /* :: */[
                          str(undefined, undefined, "What"),
                          /* [] */0
                        ],
                        undefined,
                        undefined,
                        undefined,
                        undefined,
                        undefined,
                        undefined,
                        /* () */0
                      ]),
                  /* [] */0
                ],
                Layout.style(100, 50, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* () */0),
                undefined,
                undefined,
                undefined,
                undefined,
                undefined,
                /* () */0
              ]),
          /* [] */0
        ]
      ],
      Layout.style(500, 500, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* () */0),
      undefined,
      undefined,
      undefined,
      undefined,
      undefined,
      /* () */0
    ]);

var reason = FluidDom.Fluid[/* noReason */25];

function fetch(arg, fin) {
  setTimeout(fin, 500 + Caml_int32.imul(10, Random.$$int(100)) | 0);
  return /* () */0;
}

var ImageCache = Curry._1(FluidDom.Fluid[/* Cache */26], /* module */[
      /* reason */reason,
      /* fetch */fetch
    ]);

function loading($staropt$star, hooks) {
  var children = $staropt$star !== undefined ? $staropt$star : /* [] */0;
  var match = Curry._2(FluidDom.Fluid[/* Hooks */27][/* useSuspenseHandler */1], /* () */0, hooks);
  var suspended = match[0];
  console.log("Rerender", suspended);
  if (suspended !== /* [] */0) {
    return Curry.app(FluidDom.Fluid[/* Native */28][/* div */0], [
                undefined,
                /* :: */[
                  str(undefined, undefined, "Loading " + (String(List.length(suspended)) + " items...")),
                  /* [] */0
                ],
                undefined,
                undefined,
                undefined,
                undefined,
                undefined,
                undefined,
                /* () */0
              ]);
  } else {
    return Curry.app(FluidDom.Fluid[/* Native */28][/* div */0], [
                undefined,
                children,
                undefined,
                undefined,
                undefined,
                undefined,
                undefined,
                undefined,
                /* () */0
              ]);
  }
}

function imageLoader(src, hooks) {
  Curry._1(ImageCache[/* fetch */1], src);
  return Curry.app(FluidDom.Fluid[/* Native */28][/* div */0], [
              undefined,
              /* :: */[
                Curry._3(FluidDom.Fluid[/* Native */28][/* img */2], src, Layout.style(200, 200, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* () */0), /* () */0),
                /* [] */0
              ],
              Layout.style(200, 200, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* () */0),
              undefined,
              undefined,
              undefined,
              undefined,
              "border: 3px solid red",
              /* () */0
            ]);
}

function first(hooks) {
  var partial_arg = /* :: */[
    str(undefined, undefined, "Hello"),
    /* :: */[
      Curry._4(FluidDom.Fluid[/* Native */28][/* text */5], undefined, undefined, "Hei", /* () */0),
      /* :: */[
        /* Custom */Block.__(1, [Curry._2(FluidDom.Fluid[/* Maker */7][/* makeComponent */0], imageLoader, (function (param) {
                    return imageLoader("./fluid-macos.png", param);
                  }))]),
        /* :: */[
          /* Custom */Block.__(1, [Curry._2(FluidDom.Fluid[/* Maker */7][/* makeComponent */0], imageLoader, (function (param) {
                      return imageLoader("./fluid-macos1.png", param);
                    }))]),
          /* :: */[
            /* Custom */Block.__(1, [Curry._2(FluidDom.Fluid[/* Maker */7][/* makeComponent */0], imageLoader, (function (param) {
                        return imageLoader("./fluid-macos2.png", param);
                      }))]),
            /* :: */[
              /* Custom */Block.__(1, [Curry._2(FluidDom.Fluid[/* Maker */7][/* makeComponent */0], imageLoader, (function (param) {
                          return imageLoader("./fluid-macos3.png", param);
                        }))]),
              /* :: */[
                /* Custom */Block.__(1, [Curry._2(FluidDom.Fluid[/* Maker */7][/* makeComponent */0], imageLoader, (function (param) {
                            return imageLoader("./fluid-macos4.png", param);
                          }))]),
                /* :: */[
                  /* Custom */Block.__(1, [Curry._2(FluidDom.Fluid[/* Maker */7][/* makeComponent */0], imageLoader, (function (param) {
                              return imageLoader("./fluid-macos5.png", param);
                            }))]),
                  /* [] */0
                ]
              ]
            ]
          ]
        ]
      ]
    ]
  ];
  return Curry.app(FluidDom.Fluid[/* Native */28][/* div */0], [
              "awesome",
              /* :: */[
                str(undefined, undefined, "Hello"),
                /* :: */[
                  Curry.app(FluidDom.Fluid[/* Native */28][/* div */0], [
                        "here",
                        /* :: */[
                          Curry.app(FluidDom.Fluid[/* Native */28][/* div */0], [
                                undefined,
                                /* :: */[
                                  str(undefined, undefined, "What"),
                                  /* [] */0
                                ],
                                undefined,
                                undefined,
                                undefined,
                                undefined,
                                undefined,
                                undefined,
                                /* () */0
                              ]),
                          /* [] */0
                        ],
                        Layout.style(100, 50, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* () */0),
                        undefined,
                        undefined,
                        undefined,
                        undefined,
                        "background-color: #aaa",
                        /* () */0
                      ]),
                  /* :: */[
                    /* Custom */Block.__(1, [Curry._2(FluidDom.Fluid[/* Maker */7][/* makeComponent */0], loading, (function (param) {
                                return loading(partial_arg, param);
                              }))]),
                    /* :: */[
                      /* Custom */Block.__(1, [Curry._2(FluidDom.Fluid[/* Maker */7][/* makeComponent */0], toggle, (function (param) {
                                  return toggle((function (onClick) {
                                                return Curry.app(FluidDom.Fluid[/* Native */28][/* div */0], [
                                                            undefined,
                                                            /* :: */[
                                                              str(undefined, undefined, "Click this to"),
                                                              /* :: */[
                                                                /* Custom */Block.__(1, [Curry._2(FluidDom.Fluid[/* Maker */7][/* makeComponent */0], button, (function (param) {
                                                                            return button("Turn Off", "background-color: #88ff88", onClick, param);
                                                                          }))]),
                                                                /* [] */0
                                                              ]
                                                            ],
                                                            Layout.style(undefined, undefined, undefined, /* Row */2, undefined, undefined, /* AlignCenter */2, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* () */0),
                                                            undefined,
                                                            undefined,
                                                            undefined,
                                                            undefined,
                                                            undefined,
                                                            /* () */0
                                                          ]);
                                              }), (function (onClick) {
                                                return Curry.app(FluidDom.Fluid[/* Native */28][/* div */0], [
                                                            undefined,
                                                            /* :: */[
                                                              /* Custom */Block.__(1, [Curry._2(FluidDom.Fluid[/* Maker */7][/* makeComponent */0], button, (function (param) {
                                                                          return button("Turn On", "background-color: #ffacf0", onClick, param);
                                                                        }))]),
                                                              /* :: */[
                                                                str(undefined, undefined, "if you want"),
                                                                /* [] */0
                                                              ]
                                                            ],
                                                            Layout.style(undefined, undefined, undefined, /* Row */2, undefined, undefined, /* AlignCenter */2, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* () */0),
                                                            undefined,
                                                            undefined,
                                                            undefined,
                                                            undefined,
                                                            undefined,
                                                            /* () */0
                                                          ]);
                                              }), param);
                                }))]),
                      /* :: */[
                        /* Custom */Block.__(1, [Curry._2(FluidDom.Fluid[/* Maker */7][/* makeComponent */0], awesomeComponent, (function (param) {
                                    return awesomeComponent(5, (function (prim) {
                                                  return String(prim);
                                                }), param);
                                  }))]),
                        /* :: */[
                          /* Custom */Block.__(1, [Curry._2(FluidDom.Fluid[/* Maker */7][/* makeComponent */0], awesomeComponent, (function (param) {
                                      return awesomeComponent("Hi", (function (x) {
                                                    return x;
                                                  }), param);
                                    }))]),
                          /* :: */[
                            Curry.app(FluidDom.Fluid[/* Native */28][/* div */0], [
                                  "Inner",
                                  /* :: */[
                                    str(undefined, undefined, "world"),
                                    /* [] */0
                                  ],
                                  undefined,
                                  undefined,
                                  undefined,
                                  undefined,
                                  undefined,
                                  undefined,
                                  /* () */0
                                ]),
                            /* [] */0
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ],
              Layout.style(500, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* () */0),
              undefined,
              undefined,
              undefined,
              undefined,
              undefined,
              /* () */0
            ]);
}

var match = document.getElementById("root");

if (match !== undefined) {
  Curry._2(FluidDom.Fluid[/* mount */24], /* Custom */Block.__(1, [Curry._2(FluidDom.Fluid[/* Maker */7][/* makeComponent */0], first, first)]), Js_primitive.valFromOption(match));
} else {
  throw [
        Caml_builtin_exceptions.assert_failure,
        /* tuple */[
          "App.re",
          194,
          12
        ]
      ];
}

exports.Style = Style;
exports.str = str;
exports.translate = translate;
exports.fade = fade;
exports.toggle = toggle;
exports.awesomeComponent = awesomeComponent;
exports.button = button;
exports.simple = simple;
exports.ImageCache = ImageCache;
exports.loading = loading;
exports.imageLoader = imageLoader;
exports.first = first;
/*  Not a pure module */
