// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE

import * as FluidMaker from "./FluidMaker.js";
import * as Js_primitive from "bs-platform/lib/es6/js_primitive.js";

var setDomProps = function (node,props){
      Object.keys(props).forEach(key => {
        if (key === 'checked' || key === 'value') {
          node[key] = props[key]
        } else if (typeof props[key] === 'function') {
          node[key] = props[key]
        } else {
          node.setAttribute(key, props[key])
        }
      })
    };

function createElement(typ, nativeProps) {
  var node = document.createElement(typ);
  setDomProps(node, nativeProps);
  return node;
}

function updateNativeProps(node, _, newProps) {
  return setDomProps(node, newProps);
}

function maybeUpdate(mounted, mountPoint, newElement) {
  if (mounted[/* tag */0] === newElement[/* tag */0]) {
    setDomProps(mountPoint, newElement[/* props */1]);
    return true;
  } else {
    return false;
  }
}

function inflate(param) {
  return createElement(param[/* tag */0], param[/* props */1]);
}

var NativeInterface = /* module */[
  /* setDomProps */setDomProps,
  /* createElement */createElement,
  /* updateNativeProps */updateNativeProps,
  /* maybeUpdate */maybeUpdate,
  /* inflate */inflate
];

var include = FluidMaker.F([
      maybeUpdate,
      inflate,
      (function (prim) {
          return document.createTextNode(prim);
        }),
      (function (prim, prim$1) {
          prim.textContent = prim$1;
          return /* () */0;
        }),
      (function (prim) {
          return prim.parentNode;
        }),
      (function (prim, prim$1) {
          prim.appendChild(prim$1);
          return /* () */0;
        }),
      (function (prim, prim$1, prim$2) {
          prim.insertBefore(prim$1, prim$2);
          return /* () */0;
        }),
      (function (prim, prim$1) {
          prim.removeChild(prim$1);
          return /* () */0;
        }),
      (function (prim, prim$1) {
          prim.replaceWith(prim$1);
          return /* () */0;
        })
    ]);

function div(id, _type, width, height, onclick, style, _) {
  var tmp = { };
  if (id !== undefined) {
    tmp.id = Js_primitive.valFromOption(id);
  }
  if (_type !== undefined) {
    tmp.type = Js_primitive.valFromOption(_type);
  }
  if (width !== undefined) {
    tmp.width = Js_primitive.valFromOption(width);
  }
  if (height !== undefined) {
    tmp.height = Js_primitive.valFromOption(height);
  }
  if (onclick !== undefined) {
    tmp.onclick = Js_primitive.valFromOption(onclick);
  }
  if (style !== undefined) {
    tmp.style = Js_primitive.valFromOption(style);
  }
  return /* record */[
          /* tag */"div",
          /* props */tmp
        ];
}

function button(id, _type, width, height, onclick, style, _) {
  var tmp = { };
  if (id !== undefined) {
    tmp.id = Js_primitive.valFromOption(id);
  }
  if (_type !== undefined) {
    tmp.type = Js_primitive.valFromOption(_type);
  }
  if (width !== undefined) {
    tmp.width = Js_primitive.valFromOption(width);
  }
  if (height !== undefined) {
    tmp.height = Js_primitive.valFromOption(height);
  }
  if (onclick !== undefined) {
    tmp.onclick = Js_primitive.valFromOption(onclick);
  }
  if (style !== undefined) {
    tmp.style = Js_primitive.valFromOption(style);
  }
  return /* record */[
          /* tag */"button",
          /* props */tmp
        ];
}

function input(id, _type, width, height, onchange, oninput, style, _) {
  var tmp = { };
  if (id !== undefined) {
    tmp.id = Js_primitive.valFromOption(id);
  }
  if (_type !== undefined) {
    tmp.type = Js_primitive.valFromOption(_type);
  }
  if (onchange !== undefined) {
    tmp.onchange = Js_primitive.valFromOption(onchange);
  }
  if (oninput !== undefined) {
    tmp.oninput = Js_primitive.valFromOption(oninput);
  }
  if (width !== undefined) {
    tmp.width = Js_primitive.valFromOption(width);
  }
  if (height !== undefined) {
    tmp.height = Js_primitive.valFromOption(height);
  }
  if (style !== undefined) {
    tmp.style = Js_primitive.valFromOption(style);
  }
  return /* record */[
          /* tag */"input",
          /* props */tmp
        ];
}

var Native = /* module */[
  /* div */div,
  /* button */button,
  /* input */input
];

var Fluid_001 = /* Maker */include[0];

var Fluid_002 = /* render */include[1];

var Fluid_003 = /* getNativeNode */include[2];

var Fluid_004 = /* instantiateTree */include[3];

var Fluid_005 = /* runEffect */include[4];

var Fluid_006 = /* inflateTree */include[5];

var Fluid_007 = /* listenForChanges */include[6];

var Fluid_008 = /* reconcileTrees */include[7];

var Fluid_009 = /* reconcileChildren */include[8];

var Fluid_010 = /* mount */include[9];

var Fluid = /* module */[
  /* NativeInterface */NativeInterface,
  Fluid_001,
  Fluid_002,
  Fluid_003,
  Fluid_004,
  Fluid_005,
  Fluid_006,
  Fluid_007,
  Fluid_008,
  Fluid_009,
  Fluid_010,
  /* Native */Native
];

export {
  Fluid ,
  
}
/* include Not a pure module */
