// Generated by BUCKLESCRIPT VERSION 4.0.7000, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bsb-native/lib/js/block.js");
var Curry = require("bsb-native/lib/js/curry.js");
var Layout = require("./Layout.bs.js");
var Caml_obj = require("bsb-native/lib/js/caml_obj.js");
var Belt_List = require("bsb-native/lib/js/belt_List.js");
var Pervasives = require("bsb-native/lib/js/pervasives.js");
var Js_primitive = require("bsb-native/lib/js/js_primitive.js");

function F(NativeInterface) {
  var makePending = function (inst) {
    switch (inst.tag | 0) {
      case 0 : 
          return /* PBuiltin */Block.__(0, [
                    inst[0],
                    /* Create */0,
                    Belt_List.map(inst[1], makePending),
                    inst[2]
                  ]);
      case 1 : 
          return /* PCustom */Block.__(1, [
                    /* record */[
                      /* custom */inst[0],
                      /* mountedTree : Pending */Block.__(0, [makePending(inst[1])])
                    ],
                    inst[2]
                  ]);
      case 2 : 
          return /* PNull */Block.__(2, [
                    /* Create */0,
                    inst[0]
                  ]);
      
    }
  };
  var pendingReplace = function (mounted, inst) {
    switch (inst.tag | 0) {
      case 0 : 
          return /* PBuiltin */Block.__(0, [
                    inst[0],
                    /* Replace */Block.__(0, [mounted]),
                    Belt_List.map(inst[1], makePending),
                    inst[2]
                  ]);
      case 1 : 
          return /* PCustom */Block.__(1, [
                    /* record */[
                      /* custom */inst[0],
                      /* mountedTree : Pending */Block.__(0, [pendingReplace(mounted, inst[1])])
                    ],
                    inst[2]
                  ]);
      case 2 : 
          return /* PNull */Block.__(2, [
                    /* Replace */Block.__(0, [mounted]),
                    inst[0]
                  ]);
      
    }
  };
  var makeComponent = function (identity, render) {
    return /* record */[
            /* init */(function (param) {
                return /* WithState */[/* record */[
                          /* identity */identity,
                          /* render */render,
                          /* hooks : record */[/* contents */undefined],
                          /* invalidated */false,
                          /* reconciler */undefined,
                          /* onChange */(function (param) {
                              return /* () */0;
                            })
                        ]];
              }),
            /* clone */(function (param) {
                var contents = param[0];
                if (contents[/* identity */0] === identity) {
                  if (contents[/* render */1] === render) {
                    return /* Same */925282182;
                  } else {
                    return /* `Compatible */[
                            785637236,
                            /* WithState */[/* record */[
                                /* identity */contents[/* identity */0],
                                /* render */render,
                                /* hooks */contents[/* hooks */2],
                                /* invalidated */contents[/* invalidated */3],
                                /* reconciler */contents[/* reconciler */4],
                                /* onChange */contents[/* onChange */5]
                              ]]
                          ];
                  }
                } else {
                  return /* Different */-890978471;
                }
              })
          ];
  };
  var Maker = /* module */[/* makeComponent */makeComponent];
  var runRender = function (param) {
    var component = param[0];
    var effects = /* record */[/* contents : [] */0];
    var hooks_000 = function (param) {
      component[/* invalidated */3] = true;
      return Curry._1(component[/* onChange */5], /* () */0);
    };
    var hooks_001 = function (oldData, data, reconcile) {
      component[/* reconciler */4] = /* tuple */[
        oldData,
        data,
        reconcile
      ];
      return /* () */0;
    };
    var hooks_002 = function (cleanup, fn, setCleanup) {
      effects[/* contents */0] = /* :: */[
        /* record */[
          /* cleanup */cleanup,
          /* fn */fn,
          /* setCleanup */setCleanup
        ],
        effects[/* contents */0]
      ];
      return /* () */0;
    };
    var hooks_003 = /* current */component[/* hooks */2];
    var hooks = /* record */[
      hooks_000,
      hooks_001,
      hooks_002,
      hooks_003
    ];
    component[/* invalidated */3] = false;
    var tree = Curry._1(component[/* render */1], hooks);
    return /* tuple */[
            tree,
            effects[0]
          ];
  };
  var getNativeNode = function (tree) {
    switch (tree.tag | 0) {
      case 0 : 
          return Js_primitive.some(tree[1]);
      case 1 : 
          return getNativePending(tree[0][/* mountedTree */1]);
      case 2 : 
          return Js_primitive.some(tree[0]);
      
    }
  };
  var getNativePending = function (_tree) {
    while(true) {
      var tree = _tree;
      if (tree.tag) {
        return getNativeNode(tree[0]);
      } else {
        var tree$1 = tree[0];
        switch (tree$1.tag | 0) {
          case 0 : 
              var match = tree$1[1];
              if (typeof match === "number") {
                return undefined;
              } else if (match.tag) {
                var node = match[1];
                return Js_primitive.some(node);
              } else {
                var node$1 = match[0];
                return Js_primitive.some(node$1);
              }
          case 1 : 
              _tree = tree$1[0][/* mountedTree */1];
              continue ;
          case 2 : 
              var match$1 = tree$1[0];
              if (typeof match$1 === "number") {
                return undefined;
              } else if (match$1.tag) {
                var node$2 = match$1[1];
                return Js_primitive.some(node$2);
              } else {
                var node$3 = match$1[0];
                return Js_primitive.some(node$3);
              }
          
        }
      }
    };
  };
  var getInstanceLayout = function (_element) {
    while(true) {
      var element = _element;
      switch (element.tag | 0) {
        case 0 : 
            return element[2];
        case 1 : 
            _element = element[1];
            continue ;
        case 2 : 
            return element[0];
        
      }
    };
  };
  var getMountedLayout = function (_element) {
    while(true) {
      var element = _element;
      switch (element.tag | 0) {
        case 0 : 
            return element[3];
        case 1 : 
            var match = element[0][/* mountedTree */1];
            if (match.tag) {
              _element = match[0];
              continue ;
            } else {
              return getPendingLayout(match[0]);
            }
        case 2 : 
            return element[1];
        
      }
    };
  };
  var getPendingLayout = function (_element) {
    while(true) {
      var element = _element;
      switch (element.tag | 0) {
        case 0 : 
            return element[3];
        case 1 : 
            var match = element[0][/* mountedTree */1];
            if (match.tag) {
              return getMountedLayout(match[0]);
            } else {
              _element = match[0];
              continue ;
            }
        case 2 : 
            return element[1];
        
      }
    };
  };
  var updateLayout = function (layout, children, style, measure) {
    if (layout !== undefined) {
      var layout$1 = layout;
      layout$1[/* style */1] = style;
      layout$1[/* children */9] = children;
      layout$1[/* measure */7] = measure;
      layout$1[/* layout */2] = Curry._1(Layout.Layout[/* LayoutSupport */0][/* createLayout */29], /* () */0);
      return layout$1;
    } else if (measure !== undefined) {
      return Layout.createNodeWithMeasure(children, style, measure);
    } else {
      return Layout.createNode(children, style);
    }
  };
  var instantiateTree = function (withLayout, el) {
    if (typeof el === "number") {
      return /* INull */Block.__(2, [updateLayout(withLayout, /* array */[], Layout.style(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* () */0), undefined)]);
    } else if (el.tag) {
      var custom = Curry._1(el[0][/* init */0], /* () */0);
      var match = runRender(custom);
      return /* ICustom */Block.__(1, [
                custom,
                instantiateTree(undefined, match[0]),
                match[1]
              ]);
    } else {
      var layout = el[2];
      var ichildren = Belt_List.map(el[1], (function (eta) {
              return instantiateTree(undefined, eta);
            }));
      var childLayouts = Belt_List.toArray(Belt_List.map(ichildren, getInstanceLayout));
      var style = layout !== undefined ? layout : Layout.style(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* () */0);
      return /* IBuiltin */Block.__(0, [
                el[0],
                ichildren,
                updateLayout(withLayout, childLayouts, style, el[3])
              ]);
    }
  };
  var runEffect = function (param) {
    var cleanup = param[/* cleanup */0];
    if (cleanup !== undefined) {
      Curry._1(cleanup, /* () */0);
    }
    return Curry._1(param[/* setCleanup */2], Curry._1(param[/* fn */1], /* () */0));
  };
  var mountTo = function (point, node) {
    if (point.tag) {
      return Curry._2(NativeInterface[/* appendAfter */7], point[0], node);
    } else {
      return Curry._2(NativeInterface[/* appendChild */6], point[0], node);
    }
  };
  var mountPending = function (enqueue, mount, el) {
    switch (el.tag | 0) {
      case 0 : 
          var prev = el[1];
          var $$native = el[0];
          var exit = 0;
          if (typeof prev === "number" || !prev.tag) {
            exit = 1;
          } else {
            var node = prev[1];
            Curry._3(NativeInterface[/* update */2], prev[0], node, $$native);
            var partial_arg = /* AppendChild */Block.__(0, [node]);
            return /* MBuiltin */Block.__(0, [
                      $$native,
                      node,
                      Belt_List.map(el[2], (function (param) {
                              return mountPending(enqueue, partial_arg, param);
                            })),
                      el[3]
                    ]);
          }
          if (exit === 1) {
            var layout = el[3];
            var node$1 = Curry._2(NativeInterface[/* inflate */3], $$native, layout);
            var partial_arg$1 = /* AppendChild */Block.__(0, [node$1]);
            var children = Belt_List.map(el[2], (function (param) {
                    return mountPending(enqueue, partial_arg$1, param);
                  }));
            if (typeof prev === "number") {
              mountTo(mount, node$1);
            } else if (!prev.tag) {
              Curry._2(NativeInterface[/* replaceWith */9], prev[0], node$1);
            }
            return /* MBuiltin */Block.__(0, [
                      $$native,
                      node$1,
                      children,
                      layout
                    ]);
          }
          break;
      case 1 : 
          var container = el[0];
          var custom = container[/* custom */0];
          var match = container[/* mountedTree */1];
          if (match.tag) {
            if (el[1] !== /* [] */0) {
              console.log("Warning: Unchagned node had effects");
            }
            return /* MCustom */Block.__(1, [container]);
          } else {
            var match$1 = container[/* mountedTree */1];
            var mountedTree = mountPending(enqueue, mount, match$1[0]);
            var container$1 = /* record */[
              /* custom */custom,
              /* mountedTree : Mounted */Block.__(1, [mountedTree])
            ];
            custom[0][/* onChange */5] = (function (param) {
                return Curry._1(enqueue, container$1);
              });
            Belt_List.forEach(el[1], runEffect);
            return /* MCustom */Block.__(1, [container$1]);
          }
      case 2 : 
          var prev$1 = el[0];
          var exit$1 = 0;
          if (typeof prev$1 === "number" || !prev$1.tag) {
            exit$1 = 1;
          } else {
            return /* MNull */Block.__(2, [
                      prev$1[1],
                      el[1]
                    ]);
          }
          if (exit$1 === 1) {
            var rep = Curry._1(NativeInterface[/* createNullNode */5], /* () */0);
            if (typeof prev$1 === "number") {
              mountTo(mount, rep);
            } else if (!prev$1.tag) {
              Curry._2(NativeInterface[/* replaceWith */9], prev$1[0], rep);
            }
            return /* MNull */Block.__(2, [
                      rep,
                      el[1]
                    ]);
          }
          break;
      
    }
  };
  var reconcileTrees = function (enqueue, prev, next) {
    var exit = 0;
    switch (prev.tag | 0) {
      case 0 : 
          var aLayout = prev[3];
          var node = prev[1];
          var aElement = prev[0];
          if (typeof next === "number" || next.tag) {
            exit = 1;
          } else {
            var bLayoutStyle = next[2];
            var bElement = next[0];
            if (false && Curry._3(NativeInterface[/* canUpdate */1], aElement, node, bElement)) {
              aLayout[/* style */1] = bLayoutStyle !== undefined ? bLayoutStyle : Layout.style(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* () */0);
              var children = reconcileChildren(enqueue, node, prev[2], next[1]);
              aLayout[/* children */9] = Belt_List.toArray(Belt_List.map(children, getPendingLayout));
              aLayout[/* layout */2] = Curry._1(Layout.Layout[/* LayoutSupport */0][/* createLayout */29], /* () */0);
              return /* PBuiltin */Block.__(0, [
                        bElement,
                        /* Update */Block.__(1, [
                            aElement,
                            node
                          ]),
                        children,
                        aLayout
                      ]);
            } else {
              var instances = instantiateTree(aLayout, next);
              return pendingReplace(node, instances);
            }
          }
          break;
      case 1 : 
          var a = prev[0];
          if (typeof next === "number" || !next.tag) {
            exit = 1;
          } else {
            var match = Curry._1(next[0][/* clone */1], a[/* custom */0]);
            if (typeof match === "number") {
              if (match >= 925282182) {
                return /* PCustom */Block.__(1, [
                          a,
                          /* [] */0
                        ]);
              } else {
                var instances$1 = instantiateTree(undefined, next);
                var match$1 = getNativeNode(prev);
                if (match$1 !== undefined) {
                  return pendingReplace(Js_primitive.valFromOption(match$1), instances$1);
                } else {
                  console.log("Warning! Prev custom component was pending");
                  return makePending(instances$1);
                }
              }
            } else {
              var custom = match[1];
              var match$2 = runRender(custom);
              var match$3 = a[/* mountedTree */1];
              if (match$3.tag) {
                var tree = reconcileTrees(enqueue, match$3[0], match$2[0]);
                return /* PCustom */Block.__(1, [
                          /* record */[
                            /* custom */custom,
                            /* mountedTree : Pending */Block.__(0, [tree])
                          ],
                          match$2[1]
                        ]);
              } else {
                return Pervasives.failwith("Reconciling a componenet that's still pending.");
              }
            }
          }
          break;
      case 2 : 
          exit = 1;
          break;
      
    }
    if (exit === 1) {
      var instances$2 = instantiateTree(undefined, next);
      var match$4 = getNativeNode(prev);
      if (match$4 !== undefined) {
        return pendingReplace(Js_primitive.valFromOption(match$4), instances$2);
      } else {
        console.log("Warning! Prev custom component was pending");
        return makePending(instances$2);
      }
    }
    
  };
  var reconcileChildren = function (enqueue, parentNode, aChildren, bChildren) {
    if (aChildren) {
      if (bChildren) {
        return /* :: */[
                reconcileTrees(enqueue, aChildren[0], bChildren[0]),
                reconcileChildren(enqueue, parentNode, aChildren[1], bChildren[1])
              ];
      } else {
        Belt_List.forEach(Belt_List.keepMap(aChildren, getNativeNode), Curry._1(NativeInterface[/* removeChild */8], parentNode));
        return /* [] */0;
      }
    } else if (bChildren) {
      return Belt_List.map(bChildren, (function (child) {
                    return makePending(instantiateTree(undefined, child));
                  }));
    } else {
      return /* [] */0;
    }
  };
  var enqueue = function (root, custom) {
    root[/* invalidatedElements */2] = /* :: */[
      custom,
      root[/* invalidatedElements */2]
    ];
    if (root[/* waiting */3]) {
      return 0;
    } else {
      root[/* waiting */3] = true;
      return Curry._1(NativeInterface[/* setImmediate */0], (function (param) {
                    root[/* waiting */3] = false;
                    var elements = root[/* invalidatedElements */2];
                    root[/* invalidatedElements */2] = /* [] */0;
                    var toUpdate = Belt_List.keepMap(elements, (function (container) {
                            var component = container[/* custom */0];
                            var contents = component[0];
                            if (contents[/* invalidated */3]) {
                              var match = runRender(component);
                              var newElement = match[0];
                              var match$1 = container[/* mountedTree */1];
                              if (match$1.tag) {
                                var mountedTree = match$1[0];
                                var match$2 = contents[/* reconciler */4];
                                var tmp;
                                if (match$2 !== undefined) {
                                  var match$3 = match$2;
                                  tmp = Curry._4(match$3[2], match$3[0], match$3[1], mountedTree, newElement);
                                } else {
                                  tmp = reconcileTrees((function (param) {
                                          return enqueue(root, param);
                                        }), mountedTree, newElement);
                                }
                                return /* tuple */[
                                        container,
                                        tmp,
                                        match[1]
                                      ];
                              } else {
                                console.log("Updating a pending tree...");
                                return undefined;
                              }
                            }
                            
                          }));
                    Layout.Layout[/* gCurrentGenerationCount */2][0] = Layout.Layout[/* gCurrentGenerationCount */2][0] + 1 | 0;
                    Curry._1(Layout.Layout[/* invalidateAllCaches */20], root[/* layout */0]);
                    Layout.layout(root[/* layout */0]);
                    return Belt_List.forEach(toUpdate, (function (param) {
                                  var container = param[0];
                                  Belt_List.forEach(param[2], runEffect);
                                  var match = getNativePending(container[/* mountedTree */1]);
                                  var current = match !== undefined ? Js_primitive.valFromOption(match) : Pervasives.failwith("Current is already pending");
                                  container[/* mountedTree */1] = /* Mounted */Block.__(1, [mountPending((function (param) {
                                              return enqueue(root, param);
                                            }), /* AppendChild */Block.__(0, [current]), param[1])]);
                                  return /* () */0;
                                }));
                  }));
    }
  };
  var mount = function (el, node) {
    var instances = instantiateTree(undefined, el);
    var instanceLayout = getInstanceLayout(instances);
    Layout.layout(instanceLayout);
    var root = /* record */[
      /* layout */instanceLayout,
      /* node */undefined,
      /* invalidatedElements : [] */0,
      /* waiting */false
    ];
    var tree = mountPending((function (param) {
            return enqueue(root, param);
          }), /* AppendChild */Block.__(0, [node]), makePending(instances));
    var match = getNativeNode(tree);
    if (match !== undefined) {
      var childNode = Js_primitive.valFromOption(match);
      root[/* node */1] = Js_primitive.some(childNode);
      return Curry._2(NativeInterface[/* appendChild */6], node, childNode);
    } else {
      return Pervasives.failwith("Still pending?");
    }
  };
  var useReconciler = function (data, fn, hooks) {
    var match = hooks[/* current */3][0];
    var next;
    if (match !== undefined) {
      var match$1 = match;
      Curry._3(hooks[/* setReconciler */1], match$1[0], data, fn);
      next = match$1[1];
    } else {
      next = /* record */[/* contents */undefined];
    }
    hooks[/* current */3][0] = /* tuple */[
      data,
      next
    ];
    return /* tuple */[
            /* () */0,
            hooks
          ];
  };
  var useRef = function (initial, hooks) {
    var match = hooks[/* current */3][0];
    if (match !== undefined) {
      var match$1 = match;
      return /* tuple */[
              match$1[0],
              /* record */[
                /* invalidate */hooks[/* invalidate */0],
                /* setReconciler */hooks[/* setReconciler */1],
                /* triggerEffect */hooks[/* triggerEffect */2],
                /* current */match$1[1]
              ]
            ];
    } else {
      var r = /* record */[/* contents */initial];
      var next = /* record */[/* contents */undefined];
      hooks[/* current */3][0] = /* tuple */[
        r,
        next
      ];
      return /* tuple */[
              r,
              /* record */[
                /* invalidate */hooks[/* invalidate */0],
                /* setReconciler */hooks[/* setReconciler */1],
                /* triggerEffect */hooks[/* triggerEffect */2],
                /* current */next
              ]
            ];
    }
  };
  var useState = function (initial, hooks) {
    var match = hooks[/* current */3][0];
    var match$1;
    if (match !== undefined) {
      var match$2 = match;
      match$1 = /* tuple */[
        match$2[0],
        match$2[1]
      ];
    } else {
      var next = /* record */[/* contents */undefined];
      hooks[/* current */3][0] = /* tuple */[
        initial,
        next
      ];
      match$1 = /* tuple */[
        initial,
        next
      ];
    }
    var next$1 = match$1[1];
    return /* tuple */[
            /* tuple */[
              match$1[0],
              (function (v) {
                  hooks[/* current */3][0] = /* tuple */[
                    v,
                    next$1
                  ];
                  return Curry._1(hooks[/* invalidate */0], /* () */0);
                })
            ],
            /* record */[
              /* invalidate */hooks[/* invalidate */0],
              /* setReconciler */hooks[/* setReconciler */1],
              /* triggerEffect */hooks[/* triggerEffect */2],
              /* current */next$1
            ]
          ];
  };
  var useReducer = function (initial, reducer, hooks) {
    var match = useState(initial, hooks);
    var match$1 = match[0];
    var setState = match$1[1];
    var state = match$1[0];
    return /* tuple */[
            /* tuple */[
              state,
              (function (action) {
                  return Curry._1(setState, Curry._2(reducer, state, action));
                })
            ],
            match[1]
          ];
  };
  var newEffect = function (fn, args) {
    return /* record */[
            /* args */args,
            /* cleanup : record */[/* contents */undefined],
            /* fn */fn
          ];
  };
  var useEffect = function (fn, args, hooks) {
    var match = hooks[/* current */3][0];
    var match$1;
    if (match !== undefined) {
      var match$2 = match;
      var effect = match$2[0];
      var effect$1 = Caml_obj.caml_notequal(effect[/* args */0], args) ? (Curry._3(hooks[/* triggerEffect */2], effect[/* cleanup */1][/* contents */0], fn, (function (v) {
                  effect[/* cleanup */1][/* contents */0] = v;
                  return /* () */0;
                })), /* record */[
            /* args */args,
            /* cleanup */effect[/* cleanup */1],
            /* fn */fn
          ]) : effect;
      match$1 = /* tuple */[
        effect$1,
        match$2[1]
      ];
    } else {
      var effect$2 = newEffect(fn, args);
      Curry._3(hooks[/* triggerEffect */2], effect$2[/* cleanup */1][/* contents */0], fn, (function (v) {
              effect$2[/* cleanup */1][/* contents */0] = v;
              return /* () */0;
            }));
      match$1 = /* tuple */[
        effect$2,
        /* record */[/* contents */undefined]
      ];
    }
    var next = match$1[1];
    hooks[/* current */3][0] = /* tuple */[
      match$1[0],
      next
    ];
    return /* tuple */[
            /* () */0,
            /* record */[
              /* invalidate */hooks[/* invalidate */0],
              /* setReconciler */hooks[/* setReconciler */1],
              /* triggerEffect */hooks[/* triggerEffect */2],
              /* current */next
            ]
          ];
  };
  var useMemo = function (fn, args, hooks) {
    var match = hooks[/* current */3][0];
    var match$1;
    if (match !== undefined) {
      var match$2 = match;
      var match$3 = match$2[0];
      var match$4 = Caml_obj.caml_equal(match$3[1], args);
      var value = match$4 ? match$3[0] : Curry._1(fn, /* () */0);
      match$1 = /* tuple */[
        value,
        match$2[1]
      ];
    } else {
      match$1 = /* tuple */[
        Curry._1(fn, /* () */0),
        /* record */[/* contents */undefined]
      ];
    }
    var next = match$1[1];
    var value$1 = match$1[0];
    hooks[/* current */3][0] = /* tuple */[
      /* tuple */[
        value$1,
        args
      ],
      next
    ];
    return /* tuple */[
            value$1,
            /* record */[
              /* invalidate */hooks[/* invalidate */0],
              /* setReconciler */hooks[/* setReconciler */1],
              /* triggerEffect */hooks[/* triggerEffect */2],
              /* current */next
            ]
          ];
  };
  var useCallback = function (fn, args, hooks) {
    return useMemo((function (param) {
                  return fn;
                }), args, hooks);
  };
  var Hooks = /* module */[
    /* useReconciler */useReconciler,
    /* useRef */useRef,
    /* useState */useState,
    /* useReducer */useReducer,
    /* newEffect */newEffect,
    /* useEffect */useEffect,
    /* useMemo */useMemo,
    /* useCallback */useCallback
  ];
  return /* module */[
          /* makePending */makePending,
          /* pendingReplace */pendingReplace,
          /* Maker */Maker,
          /* runRender */runRender,
          /* getNativeNode */getNativeNode,
          /* getNativePending */getNativePending,
          /* getInstanceLayout */getInstanceLayout,
          /* getMountedLayout */getMountedLayout,
          /* getPendingLayout */getPendingLayout,
          /* updateLayout */updateLayout,
          /* instantiateTree */instantiateTree,
          /* runEffect */runEffect,
          /* mountTo */mountTo,
          /* mountPending */mountPending,
          /* reconcileTrees */reconcileTrees,
          /* reconcileChildren */reconcileChildren,
          /* enqueue */enqueue,
          /* mount */mount,
          /* Hooks */Hooks
        ];
}

exports.F = F;
/* Layout Not a pure module */
