// Generated by BUCKLESCRIPT VERSION 4.0.7000, PLEASE EDIT WITH CARE
'use strict';

var Layout = require("./Layout.js");

function measureText(w, h, param, param$1, param$2, param$3, param$4) {
  return /* record */[
          /* width */w,
          /* height */h
        ];
}

var a = Layout.createNodeWithMeasure(/* array */[], Layout.style(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* () */0), (function (param, param$1, param$2, param$3, param$4) {
        return /* record */[
                /* width */30,
                /* height */50
              ];
      }));

var b = Layout.createNode(/* array */[a], Layout.style(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* () */0));

var c = Layout.createNodeWithMeasure(/* array */[], Layout.style(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* () */0), (function (param, param$1, param$2, param$3, param$4) {
        return /* record */[
                /* width */100,
                /* height */30
              ];
      }));

var d = Layout.createNode(/* array */[
      b,
      c
    ], Layout.style(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* () */0));

Layout.layout(d);

console.log(d[/* layout */2][/* width */4], d[/* layout */2][/* height */5]);

console.log(c[/* layout */2][/* top */1], c[/* layout */2][/* left */0], c[/* layout */2][/* width */4], c[/* layout */2][/* height */5]);

exports.measureText = measureText;
exports.a = a;
exports.b = b;
exports.c = c;
exports.d = d;
/* a Not a pure module */
