// Generated by BUCKLESCRIPT VERSION 4.0.7000, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bsb-native/lib/js/curry.js");
var Caml_array = require("bsb-native/lib/js/caml_array.js");
var Layout$Flex = require("/Users/jared/clone/explorations/fluid/node_modules/flex/src/lib/Layout.js");
var FloatEncoding$Flex = require("/Users/jared/clone/explorations/fluid/node_modules/flex/src/lib/FloatEncoding.js");

var nullContext = /* record */[/* contents */0];

var Node = /* module */[/* nullContext */nullContext];

var rootContext = /* record */[/* contents */0];

var Layout = Layout$Flex.Create(Node)([
      FloatEncoding$Flex.cssUndefined,
      FloatEncoding$Flex.isUndefined,
      FloatEncoding$Flex.isDefined,
      FloatEncoding$Flex.zero,
      FloatEncoding$Flex.negativeOne,
      FloatEncoding$Flex.divideScalarByInt,
      FloatEncoding$Flex.scalarToFloat,
      FloatEncoding$Flex.$neg$dot,
      FloatEncoding$Flex.$plus$dot,
      FloatEncoding$Flex.$slash$dot,
      FloatEncoding$Flex.$star$dot,
      FloatEncoding$Flex.$tilde$neg$dot,
      FloatEncoding$Flex.scalarToString
    ]);

var $$null = Layout[/* LayoutSupport */0][/* theNullNode */28];

var defaultStyle = Layout[/* LayoutSupport */0][/* defaultStyle */26];

function createNode(children, style) {
  return Curry._4(Layout[/* LayoutSupport */0][/* createNode */30], children, style, undefined, rootContext);
}

function createNodeWithMeasure(children, style, measure) {
  return Curry._4(Layout[/* LayoutSupport */0][/* createNode */30], children, style, measure, rootContext);
}

function layout(layoutNode) {
  return Curry._4(Layout[/* layoutNode */24], layoutNode, FloatEncoding$Flex.cssUndefined, FloatEncoding$Flex.cssUndefined, /* Ltr */2);
}

function style($staropt$star, $staropt$star$1, $staropt$star$2, $staropt$star$3, $staropt$star$4, $staropt$star$5, $staropt$star$6, $staropt$star$7, $staropt$star$8, $staropt$star$9, $staropt$star$10, $staropt$star$11, $staropt$star$12, $staropt$star$13, $staropt$star$14, $staropt$star$15, $staropt$star$16, $staropt$star$17, $staropt$star$18, $staropt$star$19, $staropt$star$20, param) {
  var width = $staropt$star !== undefined ? $staropt$star : FloatEncoding$Flex.cssUndefined;
  var height = $staropt$star$1 !== undefined ? $staropt$star$1 : FloatEncoding$Flex.cssUndefined;
  var flexBasis = $staropt$star$2 !== undefined ? $staropt$star$2 : FloatEncoding$Flex.cssUndefined;
  var flexDirection = $staropt$star$3 !== undefined ? $staropt$star$3 : /* Column */0;
  var flexGrow = $staropt$star$4 !== undefined ? $staropt$star$4 : FloatEncoding$Flex.cssUndefined;
  var flexShrink = $staropt$star$5 !== undefined ? $staropt$star$5 : FloatEncoding$Flex.cssUndefined;
  var alignItems = $staropt$star$6 !== undefined ? $staropt$star$6 : /* AlignFlexStart */1;
  var alignSelf = $staropt$star$7 !== undefined ? $staropt$star$7 : /* AlignAuto */0;
  var justifyContent = $staropt$star$8 !== undefined ? $staropt$star$8 : /* JustifyFlexStart */0;
  var position = $staropt$star$9 !== undefined ? $staropt$star$9 : /* Relative */0;
  var top = $staropt$star$10 !== undefined ? $staropt$star$10 : FloatEncoding$Flex.cssUndefined;
  var bottom = $staropt$star$11 !== undefined ? $staropt$star$11 : FloatEncoding$Flex.cssUndefined;
  var left = $staropt$star$12 !== undefined ? $staropt$star$12 : FloatEncoding$Flex.cssUndefined;
  var right = $staropt$star$13 !== undefined ? $staropt$star$13 : FloatEncoding$Flex.cssUndefined;
  var marginTop = $staropt$star$14 !== undefined ? $staropt$star$14 : FloatEncoding$Flex.cssUndefined;
  var marginLeft = $staropt$star$15 !== undefined ? $staropt$star$15 : FloatEncoding$Flex.cssUndefined;
  var marginRight = $staropt$star$16 !== undefined ? $staropt$star$16 : FloatEncoding$Flex.cssUndefined;
  var marginBottom = $staropt$star$17 !== undefined ? $staropt$star$17 : FloatEncoding$Flex.cssUndefined;
  var margin = $staropt$star$18 !== undefined ? $staropt$star$18 : FloatEncoding$Flex.cssUndefined;
  var marginVertical = $staropt$star$19 !== undefined ? $staropt$star$19 : FloatEncoding$Flex.cssUndefined;
  var marginHorizontal = $staropt$star$20 !== undefined ? $staropt$star$20 : FloatEncoding$Flex.cssUndefined;
  var newrecord = Caml_array.caml_array_dup(Layout[/* LayoutSupport */0][/* defaultStyle */26]);
  newrecord[/* flexDirection */1] = flexDirection;
  newrecord[/* justifyContent */2] = justifyContent;
  newrecord[/* alignItems */4] = alignItems;
  newrecord[/* alignSelf */5] = alignSelf;
  newrecord[/* positionType */6] = position;
  newrecord[/* flexGrow */10] = flexGrow;
  newrecord[/* flexShrink */11] = flexShrink;
  newrecord[/* flexBasis */12] = flexBasis;
  newrecord[/* marginLeft */13] = marginLeft;
  newrecord[/* marginTop */14] = marginTop;
  newrecord[/* marginRight */15] = marginRight;
  newrecord[/* marginBottom */16] = marginBottom;
  newrecord[/* marginHorizontal */19] = marginHorizontal;
  newrecord[/* marginVertical */20] = marginVertical;
  newrecord[/* margin */21] = margin;
  newrecord[/* width */22] = width;
  newrecord[/* height */23] = height;
  newrecord[/* left */28] = left;
  newrecord[/* top */29] = top;
  newrecord[/* right */30] = right;
  newrecord[/* bottom */31] = bottom;
  return newrecord;
}

var Encoding = 0;

var LayoutSupport = 0;

var LayoutTypes = 0;

exports.Node = Node;
exports.rootContext = rootContext;
exports.Encoding = Encoding;
exports.Layout = Layout;
exports.LayoutSupport = LayoutSupport;
exports.LayoutTypes = LayoutTypes;
exports.$$null = $$null;
exports.defaultStyle = defaultStyle;
exports.createNode = createNode;
exports.createNodeWithMeasure = createNodeWithMeasure;
exports.layout = layout;
exports.style = style;
/* Layout Not a pure module */
