// Generated by BUCKLESCRIPT VERSION 4.0.7000, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bsb-native/lib/js/block.js");
var Curry = require("bsb-native/lib/js/curry.js");
var Layout = require("./Layout.js");
var Printf = require("bsb-native/lib/js/printf.js");

function measureText(w, h, param, param$1, param$2, param$3, param$4) {
  return /* record */[
          /* width */w,
          /* height */h
        ];
}

var a = Layout.createNodeWithMeasure(/* array */[], Layout.style(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* () */0), (function (param, param$1, param$2, param$3, param$4) {
        return /* record */[
                /* width */30,
                /* height */50
              ];
      }));

var b = Layout.createNode(/* array */[a], Layout.style(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* () */0));

var c = Layout.createNodeWithMeasure(/* array */[], Layout.style(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* () */0), (function (param, param$1, param$2, param$3, param$4) {
        return /* record */[
                /* width */100,
                /* height */30
              ];
      }));

var d = Layout.createNode(/* array */[
      b,
      c
    ], Layout.style(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* () */0));

Layout.layout(d);

Curry._2(Printf.printf(/* Format */[
          /* Float */Block.__(8, [
              /* Float_f */0,
              /* No_padding */0,
              /* No_precision */0,
              /* String_literal */Block.__(11, [
                  ", ",
                  /* Float */Block.__(8, [
                      /* Float_f */0,
                      /* No_padding */0,
                      /* No_precision */0,
                      /* Char_literal */Block.__(12, [
                          /* "\n" */10,
                          /* End_of_format */0
                        ])
                    ])
                ])
            ]),
          "%f, %f\n"
        ]), d[/* layout */2][/* width */4], d[/* layout */2][/* height */5]);

Curry._4(Printf.printf(/* Format */[
          /* Float */Block.__(8, [
              /* Float_f */0,
              /* No_padding */0,
              /* No_precision */0,
              /* String_literal */Block.__(11, [
                  ", ",
                  /* Float */Block.__(8, [
                      /* Float_f */0,
                      /* No_padding */0,
                      /* No_precision */0,
                      /* String_literal */Block.__(11, [
                          ", ",
                          /* Float */Block.__(8, [
                              /* Float_f */0,
                              /* No_padding */0,
                              /* No_precision */0,
                              /* String_literal */Block.__(11, [
                                  " x ",
                                  /* Float */Block.__(8, [
                                      /* Float_f */0,
                                      /* No_padding */0,
                                      /* No_precision */0,
                                      /* Char_literal */Block.__(12, [
                                          /* "\n" */10,
                                          /* End_of_format */0
                                        ])
                                    ])
                                ])
                            ])
                        ])
                    ])
                ])
            ]),
          "%f, %f, %f x %f\n"
        ]), c[/* layout */2][/* top */1], c[/* layout */2][/* left */0], c[/* layout */2][/* width */4], c[/* layout */2][/* height */5]);

exports.measureText = measureText;
exports.a = a;
exports.b = b;
exports.c = c;
exports.d = d;
/* a Not a pure module */
